name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: build
        run: |
          npm ci
          npm run build -- --prefix-paths
      - uses: peaceiris/actions-gh-pages@v2
        env:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: gh-pages
          PUBLISH_DIR: ./docs
